wip: Feature/42/icon row my collection
desci-labs/nodes-web pull request #68
Opened 2023-04-19 15:59 UTC by polus-arcticus

closing https://github.com/desci-labs/nodes-web/issues/42

2023-04-19 17:33 UTC, polus-arcticus commented
[collections-buttons.webm](https://user-images.githubusercontent.com/122753557/233153060-d97aa649-cfa6-42f7-8301-f5bd8403436f.webm)

2023-04-21 00:03 UTC, hubsmoke commented on src/components/organisms/ComponentLibrary.tsx
> +            absolute bottom-10 scale-0 transition-all bg-[#191B1C] p-2 group-hover:scale-100
i would suggest using our tailwind preconfigured color names like neutrals-gray-5 etc in `tailwind.config.js` this is the palette our UX team is working with, so may make things easier

2023-04-21 00:04 UTC, hubsmoke commented on src/components/organisms/PaneNodeCollection.tsx
> +      {showUploadPanel && <UploadPanel show={showUploadPanel} />}
please add tooltip with component name instead of upload action

2023-04-21 00:05 UTC, hubsmoke commented on src/components/molecules/NodeCard.tsx
> +        {isCurrent && <ComponentLibraryList />}
please construct the list based on the components in the Node's manifest, found in the manifest/manifestData state in the `useNodeReader` hook

2023-04-21 00:07 UTC, hubsmoke requested changes
great work so far, i left some comments and followed up via discord

2024-01-03 18:07 UTC, closed without merging